apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  labels:
    name: "jenkins"
    app: "jenkins"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "jenkins"
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: "jenkins"
          image: yaramohamed/jenkins:docker
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
          - name: docker
            mountPath: /var/run/docker.sock
      volumes:
      - name: docker
        hostPath:
          path: /var/run/docker.sock
