apiVersion: v1
kind: Service
metadata:
  name: "jenkins"
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: "jenkins"
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      nodePort: 30000
  selector:
    app: "jenkins"
  type: NodePort

